version: "3.9"

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./db/app
        target: /app/db
      - type: bind
        source: ./data
        target: /app/data